version: '3'

services:
    web:
        build: .
        command: python /code/manage.py collectstatic
        command: python /code/manage.py runserver 0.0.0.0:8000
        command: gunicorn iron_project.wsgi -b 0.0.0.0:8000
        environment:
            - ENVIRONMENT=production
            - SECRET_KEY=mjq6#5l-i^fe9=39d&xv*nl)91k10*n4xw9b!ci7^kq-*r32q$$
            - DEBUG=0
        ports:
            - 8000:8000
        depends_on: 
            - db
    db:
        image: postgres:11
        


