version: '3'

services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        environment:
            - SECRET_KEY=mjq6#5l-i^fe9=39d&xv*nl)91k10*n4xw9b!ci7^kq-*r32q$$
            - DEBUG=1
        ports:
            - 8000:8000
        depends_on: 
            - db
    db:
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

volumes:
    postgres_data:

